version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: attendance-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-attendance}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - attendance-network

  # Backend API
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: attendance-backend
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-attendance}?authSource=admin
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${BACKEND_PORT:-3000}
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - attendance-network

  # Frontend Application
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: attendance-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASEURL: ${VITE_API_BASEURL:-http://localhost:3000}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - attendance-network

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  attendance-network:
    driver: bridge